spring:
  datasource:
    url: jdbc:postgresql://ec2-3-89-0-52.compute-1.amazonaws.com:5432/df5hsgmhd74mnh
    username: ypmzkpencdrktt
    password: ba4880f3cb7c9d5ae56b7c4520f724a97542347dd2761441b87cb2105b43f681
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true