spring:
  datasource:
    url: jdbc:postgresql://ec2-54-208-139-247.compute-1.amazonaws.com:5432/d9jifq15g5cj1u
    username: iwufelfymlzgau
    password: 0b4b796c43926f48275d964c14446707dfba0a039bbccca070d45c8642f6c7d4
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
